# Generated by Django 3.2.8 on 2021-10-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='name',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
