# Generated by Django 3.2.8 on 2021-10-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_alter_wine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='bio',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
